# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'AVFoundationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVFoundationDemo
  pod 'Hue', '~> 5.0.0'
  pod 'SnapKit', '~> 5.7.1'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'  # 设为你的目标版本
    end
  end
end
